name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install NTL
      run: sh install_ntl.sh
      
    - name: Create a Makefile with Cmake
      run: cmake .
    
    - name: Compile the code
      run: make
  
    - name: Run tests to confirm the library works
      run: make test
